"""added tables

Revision ID: e3db85820e21
Revises: 
Create Date: 2018-12-02 17:30:04.053480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db85820e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('meet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meet_city'), 'meet', ['city'], unique=False)
    op.create_index(op.f('ix_meet_description'), 'meet', ['description'], unique=False)
    op.create_index(op.f('ix_meet_title'), 'meet', ['title'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('this_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['this_id'], ['meet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_address'), 'event', ['address'], unique=False)
    op.create_index(op.f('ix_event_city'), 'event', ['city'], unique=False)
    op.create_index(op.f('ix_event_description'), 'event', ['description'], unique=False)
    op.create_index(op.f('ix_event_state'), 'event', ['state'], unique=False)
    op.create_index(op.f('ix_event_time'), 'event', ['time'], unique=False)
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.drop_index(op.f('ix_event_time'), table_name='event')
    op.drop_index(op.f('ix_event_state'), table_name='event')
    op.drop_index(op.f('ix_event_description'), table_name='event')
    op.drop_index(op.f('ix_event_city'), table_name='event')
    op.drop_index(op.f('ix_event_address'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_meet_title'), table_name='meet')
    op.drop_index(op.f('ix_meet_description'), table_name='meet')
    op.drop_index(op.f('ix_meet_city'), table_name='meet')
    op.drop_table('meet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
