"""GuessList table added

Revision ID: ffdf38a30986
Revises: e3db85820e21
Create Date: 2018-12-10 22:32:05.987035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdf38a30986'
down_revision = 'e3db85820e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guess_list_username'), 'guess_list', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guess_list_username'), table_name='guess_list')
    op.drop_table('guess_list')
    # ### end Alembic commands ###
